import React from 'react';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import MeshBackground from '../components/layout/MeshBackground';

interface TermsSection {
  heading: string;
  content: React.ReactNode;
}

const SECTIONS: TermsSection[] = [
  {
    heading: 'Acceptance of Terms',
    content: (
      <p>
        By accessing or using the CIBWatch web-based detection tool, you agree to be bound by these Terms
        of Service. If you do not agree with any part of these terms, you may not use our system.
      </p>
    ),
  },
  {
    heading: 'Nature of the System & Intended Use',
    content: (
      <p>
        CIBWatch is an experimental, unsupervised machine learning prototype designed to aid human
        investigators in identifying structural anomalies in digital discourse. The system is intended strictly for
        research, academic, and journalistic use by civic defenders and election watchdogs.
      </p>
    ),
  },
  {
    heading: 'Machine Learning Disclaimer & Limitation of Liability',
    content: (
      <>
        <p className="mb-3">
          You explicitly acknowledge and agree to the following limitations regarding our system outputs:
        </p>
        <ul className="list-disc list-outside ml-5 space-y-2">
          <li>
            <strong>Mathematical Approximations:</strong> The CIB Risk Scores, Anomaly Flags, and SHAP Feature
            Attributions are mathematical probabilities generated by an Isolation Forest algorithm. They detect
            unnatural, mechanical behavior patterns.
          </li>
          <li>
            <strong>Not Definitive Proof:</strong> A "High Risk" classification does not constitute definitive legal
            proof or a factual accusation that a specific individual is a malicious actor, troll, or bot.
          </li>
          <li>
            <strong>Human Verification Required:</strong> CIBWatch outputs are meant to be the starting point for
            human-led investigations, not the conclusion. We shall not be held liable for any claims, damages,
            defamation, or legal actions arising from how users interpret, publish, or act upon the data and
            visualizations provided by this tool.
          </li>
        </ul>
      </>
    ),
  },
  {
    heading: 'Prohibited Uses',
    content: (
      <>
        <p className="mb-3">You agree not to use CIBWatch to:</p>
        <ul className="list-disc list-outside ml-5 space-y-1.5">
          <li>Harass, dox, intimidate, or unlawfully expose individuals.</li>
          <li>Make definitive public accusations without conducting independent, human-led verification.</li>
          <li>
            Attempt to reverse-engineer our SHA-256 cryptographic hashing to expose anonymized user identities.
          </li>
          <li>Overload, scrape, or intentionally disrupt our backend API infrastructure.</li>
        </ul>
      </>
    ),
  },
  {
    heading: 'Modifications to the Service',
    content: (
      <p>
        CIBWatch is a research prototype; we reserve the right to modify, suspend, or discontinue the service
        (or any part thereof), including resetting our databases, at any time without prior notice.
      </p>
    ),
  },
];

export default function TermsOfService() {
  return (
    <div className="min-h-screen font-['Inter'] bg-[#F8FAFC] flex flex-col relative overflow-hidden">

      <MeshBackground />
      <Navbar />

      {/* Header */}
      <div className="relative z-10 text-center pt-32 pb-12 px-6">
        <h1 className="text-5xl font-extrabold font-['Plus_Jakarta_Sans'] text-gray-900 mb-3 tracking-tight">
          Terms of Services
        </h1>
        <p className="text-gray-500 text-[14px] font-medium">Effective Date: June 2026</p>
      </div>

      {/* Content */}
      <main className="max-w-[860px] w-full mx-auto px-6 relative z-10 flex-grow mb-28">
        <div className="space-y-12">
          {SECTIONS.map((section) => (
            <div key={section.heading}>
              <h2 className="text-2xl font-extrabold font-['Plus_Jakarta_Sans'] text-gray-900 mb-4">
                {section.heading}
              </h2>
              <div className="text-gray-700 text-[15px] leading-relaxed">
                {section.content}
              </div>
            </div>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}